# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: jutive
open_collective: N/A
ko_fi: N/A
tidelift: N/A
community_bridge: N/A
liberapay: jutive
issuehunt: N/A
otechie: N/A
custom: https://jutive.com/support-us
